In [3]:
import numpy as np

In [3]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [4]:
a=[1,2,3,4]
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
b= np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [7]:
b=np.array([1,2,3,4])
b*2

array([2, 4, 6, 8])

In [11]:
a= np.arange(1,10,2.5)
a

array([1. , 3.5, 6. , 8.5])

In [12]:
b= np.arange(1,13)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
c= np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [15]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [16]:
e=np.array(((1,2),(3,4)))
e

array([[1, 2],
       [3, 4]])

In [19]:
a=np.array([-1,0,1.0,100],dtype='int8')
a

array([ -1,   0,   1, 100], dtype=int8)

In [20]:
a*2
# 2*100 greater than the bit (128)

array([ -2,   0,   2, -56], dtype=int8)

In [21]:
b=a.astype('float32')
b

array([ -1.,   0.,   1., 100.], dtype=float32)

In [22]:
a=[1,2,3]
a.append(4)
a

[1, 2, 3, 4]

In [25]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a[0]

0

In [27]:
a[-1]

11

In [28]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a[2:7]

array([2, 3, 4, 5, 6])

In [30]:
a[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [32]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [33]:
b=a.reshape(3,4)
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [34]:
b[0:1]

array([[100,   1,   2,   3]])

In [38]:
b[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [39]:
b[:,::2]

array([[100,   2],
       [  4,   6],
       [  8,  10]])

In [40]:
b[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [41]:
b[:,-1]


array([ 3,  7, 11])

## 3d tensor

In [45]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
c[1,1,1]

17

In [47]:
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
c[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [51]:
a*2
#vectorization

array([ 2,  4,  6,  8, 10])

In [52]:
a+10

array([11, 12, 13, 14, 15])

In [54]:
a<3

array([ True,  True, False, False, False])

In [55]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [56]:
a

array([1, 2, 3, 4, 5])

In [57]:
a+b

array([1, 3, 5, 7, 9])

In [58]:
a*b

array([ 0,  2,  6, 12, 20])

In [59]:
a.dot(b)
#matrix multiplication and the result is scaler

40

In [60]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
c=np.arange(12).reshape(1,12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [62]:
d=np.arange(12).reshape(12,1)
d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [66]:
a.dot(a)

55

In [67]:
c.dot(d)

array([[506]])

In [68]:
d.dot(c)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121]])

In [69]:
a =np.arange(3)
a.shape

(3,)

In [72]:
b=np.arange(3).reshape(1,3)
b.shape


(1, 3)

In [73]:
c=np.arange(3).reshape(3,1)
c.shape

(3, 1)

In [74]:
b.T

array([[0],
       [1],
       [2]])

In [75]:
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## masking

In [77]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
a>1

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [79]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
b=np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [83]:
b[b>15].reshape(7,2)

array([[16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [4]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [7]:
b=a.reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [8]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [9]:
c=a[:15]
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [11]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [12]:
b

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [13]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [15]:
d=a[a>15]
d

array([100,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29])

In [17]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
b=a.reshape(6,-1)
b
#-1 should be figure pot the dimension on its on 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
b.flatten()
#it make the vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b.reshape(1,12)
# it make the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones(4)*7

array([7., 7., 7., 7.])

In [33]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [34]:
np.empty((4,5))
# prints out the garbage values

array([[1.16443244e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 8.45604119e-307],
       [5.30276956e+180, 3.31033942e-033, 6.97397587e-076,
        5.06557762e-086, 3.35610365e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 3.27613900e+179],
       [9.33347272e+164, 5.97978002e+174, 1.59853949e+160,
        4.92432826e-143, 1.50008929e+248]])

In [37]:
np.eye(3,4)
#not necessary to be square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
np.identity(4)
#necessary to be square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.linspace(1,5,9)
# similar to arange bur the thirs part is the partition 

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [43]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

## Analysis

In [44]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
a.sum()

66

In [47]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b.sum()

66

In [51]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [50]:
b.sum(1)

array([ 6, 22, 38])

In [52]:
c= np.arange(24).reshape(4,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [53]:
c.sum(axis=0)
#axis o collaps with depth

array([[36, 40],
       [44, 48],
       [52, 56]])

In [54]:
c.sum(axis=1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])

In [56]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b.max()

11

In [60]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [62]:
b.mean(axis=1)

array([1.5, 5.5, 9.5])

In [66]:
np.median(b,axis=0)


array([4., 5., 6., 7.])

In [65]:
np.mean(b)

5.5

In [70]:
np.std(b,axis=1)
#stabdard deviation is says how spread out the data

array([1.11803399, 1.11803399, 1.11803399])

In [74]:
90 + np.random.rand(4,5)*10
#it gives randm numbers and all are between 0 and 1

array([[97.04073191, 97.63896558, 91.78488859, 90.39408872, 91.1473795 ],
       [99.74007934, 94.76813557, 93.30812836, 99.73435261, 94.32819458],
       [97.81893136, 90.12398488, 90.77455925, 93.15818872, 93.28283276],
       [94.64624939, 93.11833392, 96.77532737, 96.63616973, 96.56604068]])

In [76]:
np.random.randint(50,60,5)
# the last one says number of occurrrence

array([54, 57, 55, 56, 56])

In [78]:
np.random.seed(32)
np.random.rand()

0.8588892672930397

In [80]:
mu=100
sigma=15
s=np.random.normal(mu,sigma,100)
s

array([100.38324942, 110.44440519, 109.15172018, 122.42939313,
        99.68335671,  59.71689516, 116.91458811, 112.67501441,
       101.2606249 ,  91.32276052, 107.23132485,  80.88451447,
        79.07400215,  67.13655606,  63.35053673, 102.75318733,
        82.69267257, 103.94834947, 111.33951808, 110.94163496,
       104.82179362, 100.7289644 ,  97.47563412,  77.87847596,
       106.15934288, 118.75349069,  73.04620372,  82.21195122,
       114.55761317, 122.56921371,  97.96751608,  91.80327749,
       123.66731804,  97.86080827,  78.70914467, 104.63355246,
        91.75481242,  93.95222163, 108.96255327,  86.12614084,
       125.44889216, 107.88124365,  98.80097528,  80.92695662,
       102.70380568, 117.8147723 ,  85.04854371,  83.58309012,
       106.55889486, 110.34100934,  86.16297769,  71.54145703,
        90.69005368,  86.66434063,  81.31615419, 103.36201854,
        99.83404523,  87.19966159,  91.1527041 , 101.49212594,
       102.27979363,  96.00136277, 116.54487232, 104.71

In [81]:
np.mean(s)

99.76185161349147

In [82]:
np.std(s)

15.383635221117911

## Sorting

In [85]:
d=np.random.randint(1,9,(3,4))
d

array([[1, 4, 6, 2],
       [8, 8, 8, 2],
       [5, 7, 3, 7]])

In [86]:
d.sort()

In [87]:
d

array([[1, 2, 4, 6],
       [2, 8, 8, 8],
       [3, 5, 7, 7]])

In [94]:
d=d.flatten()

In [96]:
d.sort()
d

array([1, 2, 2, 3, 4, 5, 6, 7, 7, 8, 8, 8])

In [98]:
d= d.reshape(3,4)

In [99]:
d

array([[1, 2, 2, 3],
       [4, 5, 6, 7],
       [7, 8, 8, 8]])